//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personnel.Client.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Personnel.Client.Client.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string BtnContinum {
            get {
                return ResourceManager.GetString("BtnContinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string BtnSend {
            get {
                return ResourceManager.GetString("BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviando.
        /// </summary>
        public static string BtnSending {
            get {
                return ResourceManager.GetString("BtnSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validando.
        /// </summary>
        public static string BtnValiding {
            get {
                return ResourceManager.GetString("BtnValiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambos campos son obligatorios para completar tu registro..
        /// </summary>
        public static string CheckInSubtitle {
            get {
                return ResourceManager.GetString("CheckInSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido,.
        /// </summary>
        public static string CheckInSuccess {
            get {
                return ResourceManager.GetString("CheckInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu registro de entrada ha sido completado con éxito..
        /// </summary>
        public static string checkInSuccessSubtitle {
            get {
                return ResourceManager.GetString("checkInSuccessSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para registrar tu entrada, por favor ingresa tu información..
        /// </summary>
        public static string CheckInTitle {
            get {
                return ResourceManager.GetString("CheckInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola!.
        /// </summary>
        public static string CheckInTitleHi {
            get {
                return ResourceManager.GetString("CheckInTitleHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola!.
        /// </summary>
        public static string checkOutTitleHi {
            get {
                return ResourceManager.GetString("checkOutTitleHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Gracias! Si coincide con una dirección de correo electrónico que tenemos registrada, entonces te hemos enviado un correo con instrucciones adicionales para que puedas restablecer la contraseña..
        /// </summary>
        public static string ComplitSendForget {
            get {
                return ResourceManager.GetString("ComplitSendForget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reiniciar.
        /// </summary>
        public static string CreateQRBtnReset {
            get {
                return ResourceManager.GetString("CreateQRBtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir.
        /// </summary>
        public static string CreateQrBtnShare {
            get {
                return ResourceManager.GetString("CreateQrBtnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido.
        /// </summary>
        public static string CreateQrLabelContent {
            get {
                return ResourceManager.GetString("CreateQrLabelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear QR.
        /// </summary>
        public static string CreateQRTitle {
            get {
                return ResourceManager.GetString("CreateQRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Revisa tu correo electrónico.
        /// </summary>
        public static string ForgotCheckEmail {
            get {
                return ResourceManager.GetString("ForgotCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Se te olvido tu contraseña?.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesion.
        /// </summary>
        public static string LogInTitle {
            get {
                return ResourceManager.GetString("LogInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string MailText {
            get {
                return ResourceManager.GetString("MailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string NewPasswordTitle {
            get {
                return ResourceManager.GetString("NewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string PasswordTitleConfirme {
            get {
                return ResourceManager.GetString("PasswordTitleConfirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, solicita un nuevo enlace para restablecer tu contraseña..
        /// </summary>
        public static string ResetPassowrMessage {
            get {
                return ResourceManager.GetString("ResetPassowrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra minúscula (a-z).
        /// </summary>
        public static string ResetPasswordLowercaseReq {
            get {
                return ResourceManager.GetString("ResetPasswordLowercaseReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una letra mayúscula (A-Z).
        /// </summary>
        public static string ResetPasswordMay {
            get {
                return ResourceManager.GetString("ResetPasswordMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo 8 caracteres.
        /// </summary>
        public static string ResetPasswordMinLength {
            get {
                return ResourceManager.GetString("ResetPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El enlace que utilizaste para restablecer tu contraseña ya no es válido. Por motivos de seguridad, los enlaces tienen un tiempo limitado de uso..
        /// </summary>
        public static string ResetPasswordNotValidtoken {
            get {
                return ResourceManager.GetString("ResetPasswordNotValidtoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un número (0-9).
        /// </summary>
        public static string ResetPasswordNumberReq {
            get {
                return ResourceManager.GetString("ResetPasswordNumberReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar nuevo enlace .
        /// </summary>
        public static string ResetPasswordRepeatToken {
            get {
                return ResourceManager.GetString("ResetPasswordRepeatToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe cumplir con los siguientes requisitos:.
        /// </summary>
        public static string ResetPasswordRequirements {
            get {
                return ResourceManager.GetString("ResetPasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar nueva contraseña.
        /// </summary>
        public static string ResetPasswordSend {
            get {
                return ResourceManager.GetString("ResetPasswordSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un carácter especial (!@#$%).
        /// </summary>
        public static string ResetPasswordSpecialCharReq {
            get {
                return ResourceManager.GetString("ResetPasswordSpecialCharReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa tu nueva contraseña a continuación..
        /// </summary>
        public static string ResetPasswordSubtitle {
            get {
                return ResourceManager.GetString("ResetPasswordSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Contraseña actualizada!.
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu contraseña se ha cambiado con éxito. A partir de ahora, usa tu nueva contraseña para iniciar sesión..
        /// </summary>
        public static string ResetPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ResetPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer tu contraseña.
        /// </summary>
        public static string ResetPasswordtitle {
            get {
                return ResourceManager.GetString("ResetPasswordtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El enlace ha caducado.
        /// </summary>
        public static string ResetTokenNotValid {
            get {
                return ResourceManager.GetString("ResetTokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar al inicio de sesión .
        /// </summary>
        public static string ReturnLgoInTitle {
            get {
                return ResourceManager.GetString("ReturnLgoInTitle", resourceCulture);
            }
        }
    }
}
