USE[RUBNS_AUTH]
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Users')
BEGIN
CREATE TABLE Users
(
	UserID INT IDENTITY (1,1) NOT NULL CONSTRAINT PK_USERS_ID PRIMARY KEY CLUSTERED (UserID)
	,Name NVARCHAR(100) COLLATE Latin1_General_CI_AI NOT NULL
	,Email NVARCHAR(100)  COLLATE Latin1_General_CI_AI NOT NULL
	,Password NVARCHAR(MAX) NOT NULL
	,Phone NVARCHAR(50)  COLLATE Latin1_General_CI_AI NOT NULL
	,RolID INT NULL DEFAULT (3)
	,Status bit null
	,Registed DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)')
)
END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CheckPersonal')
BEGIN
CREATE TABLE CheckPersonal
(
	CheckPersonalID INT IDENTITY (1,1) NOT NULL CONSTRAINT PK_CheckPersonal_ID PRIMARY KEY CLUSTERED (CheckPersonalID)
	,UserID INT NOT NULL
	,LatitudeCheckIn DECIMAL(11,8) NULL
	,LongitudeCheckIn DECIMAL(11,8) NULL
	,LatitudeCheckOut DECIMAL(11,8) NULL
	,LongitudeCheckOut DECIMAL(11,8) NULL
	,IP NVARCHAR(100) NULL
	,RegistedCheckIn DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)')
	,RegistedCheckOut DATETIMEOFFSET 
)
END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Rols')
BEGIN
CREATE TABLE Rols
(
	RolID INT IDENTITY (1,1) NOT NULL CONSTRAINT PK_Rols_ID PRIMARY KEY CLUSTERED (RolID)
	,Name NVARCHAR(100) COLLATE Latin1_General_CI_AI NOT NULL
	,Value NVARCHAR(100) NOT NULL
	,LevelPermission INT NOT NULL
	,Status BIT 
	,Registed DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)')
)
END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Templates')
BEGIN
CREATE TABLE Templates
(
	TemplateID INT IDENTITY (1,1) NOT NULL CONSTRAINT PK_TEMPLATE_ID PRIMARY KEY CLUSTERED (TemplateID)
	,Name NVARCHAR(100) COLLATE Latin1_General_CI_AI NOT NULL 
	,Value NVARCHAR(MAX) COLLATE Latin1_General_CI_AI NOT NULL 
	,Registed DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)')
)
END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'SessionUsers')
BEGIN
CREATE TABLE SessionUsers
(
	 ID INT IDENTITY (1,1) NOT NULL CONSTRAINT PK_SessionUsers_ID PRIMARY KEY CLUSTERED (ID)
	,UserID INT NOT NULL
	,Token NVARCHAR(MAX) NOT NULL
	,Expiration  DATETIMEOFFSET NOT NULL
	,Registed DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)')
)
END
GO
IF NOT EXISTS(SELECT 1
FROM sys.database_principals dp
LEFT JOIN sys.database_permissions dpr ON dp.principal_id = dpr.grantee_principal_id
WHERE dp.name = 'auth')
BEGIN
	CREATE LOGIN [auth] 
	WITH PASSWORD = 'Temporal1',
		 CHECK_POLICY = OFF;  

	CREATE USER [auth] FOR LOGIN [auth];

	-- Otorgar roles básicos (lectura y escritura)
	ALTER ROLE db_datareader ADD MEMBER [auth];
	ALTER ROLE db_datawriter ADD MEMBER [auth];
	ALTER ROLE db_ddladmin ADD MEMBER [auth];
	GRANT EXECUTE TO [auth];

	-- (Opcional) Si quieres que tenga control total dentro de la base de datos:
	-- ALTER ROLE db_owner ADD MEMBER [auth];

END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ResetPasswords')
BEGIN
CREATE TABLE ResetPasswords
(
	ResetPasswordID INT IDENTITY (1,1) NOT NULL CONSTRAINT PK_RESETPASSWORD_ID PRIMARY KEY CLUSTERED (ResetPasswordID)
	,UserID INT 
	,Token NVARCHAR(100)
	,Registed DATETIME NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)')
	CONSTRAINT FK_USERS FOREIGN KEY (UserID)
    REFERENCES Users(UserID)
)
END
GO
CREATE or ALTER FUNCTION dbo.DistanceMts (@latCheck FLOAT, @lonCheck FLOAT)
RETURNS FLOAT
AS
BEGIN
	DECLARE @RadioTierra FLOAT = 6371000; -- en metros
	DECLARE @latHomeRad FLOAT, @lonHomeRad FLOAT;
	DECLARE @latCheckRad FLOAT, @lonCheckRad FLOAT;
	DECLARE @deltaLat FLOAT, @deltaLon FLOAT;
	DECLARE @a FLOAT, @c FLOAT, @distanciaMetros FLOAT;

	-- Coordenadas del punto base
	SELECT 
		@latHomeRad = RADIANS(ch.LatitudeCheckIn),
		@lonHomeRad = RADIANS(ch.LongitudeCheckIn)
	FROM dbo.CheckPersonal AS ch
	WHERE ch.CheckPersonalID = 0;

	-- Coordenadas del punto a comprobar

	SET	@latCheckRad = RADIANS(@latCheck);
	SET	@lonCheckRad = RADIANS(@lonCheck)


	-- Diferencias
	SET @deltaLat = @latCheckRad - @latHomeRad;
	SET @deltaLon = @lonCheckRad - @lonHomeRad;

	-- Fórmula de Haversine
	SET @a = POWER(SIN(@deltaLat / 2), 2) + COS(@latHomeRad) * COS(@latCheckRad) * POWER(SIN(@deltaLon / 2), 2);
	SET @c = 2 * ASIN(SQRT(@a));
	SET @distanciaMetros = @RadioTierra * @c;

	-- Resultado
	RETURN @distanciaMetros
END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Links')
BEGIN
CREATE TABLE dbo.Links
(
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_LINK_ID PRIMARY KEY CLUSTERED,
    Name NVARCHAR(100) COLLATE Latin1_General_CI_AI NOT NULL,
	Slug NVARCHAR(100) COLLATE Latin1_General_CI_AI NOT NULL,
    Content NVARCHAR(MAX) COLLATE Latin1_General_CI_AI NOT NULL,
	Url NVARCHAR(MAX) COLLATE Latin1_General_CI_AI NOT NULL,
	UserID INT NOT NULL,
    Status BIT NULL,
    Registered DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)'),
	LastModificated DATETIMEOFFSET  DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)'),
	LastUserID INT NOT NULL,
)
END
GO
CREATE UNIQUE NONCLUSTERED INDEX ix_Link_Slug
ON dbo.Links (Slug);
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'QRs')
BEGIN
CREATE TABLE dbo.QRs
(
    Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_QR_ID PRIMARY KEY CLUSTERED,
	LinkId INT NOT NULL CONSTRAINT FK_QRS_LINKS FOREIGN KEY (LinkId) REFERENCES dbo.links(ID),
	ColorDark NVARCHAR(15) default '#000000',
	ColorLight NVARCHAR(15) default '#FFFFFF',
	DotScale float default 1.0,
	QuietZone int default 20,
	LastModificated DATETIMEOFFSET  DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)'),
	LastUserID INT NOT NULL,
)
END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Clicks')
BEGIN
CREATE TABLE dbo.Clicks
(
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Clicks_ID PRIMARY KEY CLUSTERED,
    LinkId INT NOT NULL CONSTRAINT FK_CLICKS_LINKS FOREIGN KEY (LinkId) REFERENCES Links(Id),
    ClickedAt DATETIMEOFFSET  DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)'),
    Country NVARCHAR(100) NULL,
    Region NVARCHAR(100) NULL,
    City NVARCHAR(100) NULL,
    DeviceType NVARCHAR(50) NULL,       -- Ej: Desktop, Mobile, Tablet
    OS NVARCHAR(50) NULL,               -- Ej: Windows, iOS, Android
    Browser NVARCHAR(50) NULL,          -- Ej: Chrome, Edge, Safari
    IpAddress NVARCHAR(45) NULL,        -- IPv4 o IPv6
)
END
GO
IF NOT EXISTS (
	SELECT 1
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'JobLogs')

BEGIN
	CREATE TABLE JobLogs
	(
		ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_JOBLOGS_ID  PRIMARY KEY  CLUSTERED(ID),
		JobName NVARCHAR(100) NOT NULL,
		Executed DATETIMEOFFSET NOT NULL DEFAULT (SYSDATETIMEOFFSET() AT TIME ZONE 'Central Standard Time (Mexico)'),
		DeleteRows INT NULL,
		MessageError NVARCHAR(MAX)
	)
END